(() => {
  const root = document.getElementById("comments"), slug = root?.dataset.postSlug;
  const siteKey = root?.dataset.turnstileKey || "", list = document.getElementById("comment-list");
  const form = document.getElementById("comment-form"), status = document.getElementById("comment-status");
  const withdrawal = document.getElementById("withdrawal");
  if (!slug || !list || !form) return;
  let turnstileToken = "", commentId = "";
  const text = (value) => String(value ?? "");
  const render = (items) => { list.replaceChildren(); if (!items.length) { const empty = document.createElement("p"); empty.className = "muted"; empty.textContent = "No approved comments yet."; list.append(empty); return; } items.forEach((item) => { const card = document.createElement("div"); card.className = "card"; const head = document.createElement("strong"); head.textContent = text(item.author_name); const body = document.createElement("p"); body.textContent = text(item.body); card.append(head, body); list.append(card); }); };
  fetch(`/api/public/comments?post=${encodeURIComponent(slug)}`).then((r) => r.ok ? r.json() : Promise.reject()).then((json) => render(Array.isArray(json.data) ? json.data : [])).catch(() => { list.textContent = "Comments are temporarily unavailable."; });
  let turnstileWidgetId = null;
  const renderTurnstile = () => { if (siteKey && window.turnstile) turnstileWidgetId = window.turnstile.render(document.getElementById("comment-turnstile"), { sitekey: siteKey, callback: (token) => { turnstileToken = token; }, "expired-callback": () => { turnstileToken = ""; }, "error-callback": () => { turnstileToken = ""; } }); };
  if (siteKey && !window.turnstile) { const script = document.createElement("script"); script.src = "https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit"; script.async = true; script.onload = renderTurnstile; document.head.append(script); } else renderTurnstile();
  form.addEventListener("submit", async (event) => { event.preventDefault(); status.textContent = "Submitting…"; const response = await fetch("/api/public/comments", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ post_slug: slug, author_name: document.getElementById("comment-author").value.trim(), body: document.getElementById("comment-body").value.trim(), turnstile_token: turnstileToken }) }).catch(() => null); if (response?.ok) { const json = await response.json(); status.textContent = "Submitted and awaiting moderation."; commentId = text(json.data?.id); const token = text(json.data?.withdrawal_token); if (token && withdrawal) { document.getElementById("withdrawal-token").textContent = token; withdrawal.hidden = false; document.getElementById("withdraw-input").value = token; } form.reset(); } else status.textContent = "Submission failed; please try again later."; turnstileToken = ""; if (turnstileWidgetId !== null && window.turnstile?.reset) window.turnstile.reset(turnstileWidgetId); });
  document.getElementById("withdraw-form")?.addEventListener("submit", async (event) => { event.preventDefault(); const response = await fetch(`/api/public/comments/${encodeURIComponent(commentId)}/withdraw`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ withdrawal_token: document.getElementById("withdraw-input").value }) }); document.getElementById("withdraw-status").textContent = response.status === 204 ? "Comment withdrawn." : "Comment not found."; if (response.status === 204) withdrawal.hidden = true; });
})();
